# Generated by Django 4.1.3 on 2022-12-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='privateRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.CharField(max_length=200)),
                ('member2', models.CharField(max_length=200)),
                ('pid', models.IntegerField(default=0)),
            ],
        ),
    ]
