# Generated by Django 4.1.3 on 2022-12-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChatSite', '0002_privateroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mid',
            new_name='room_nr',
        ),
    ]
